create extension if not exists pgcrypto;
create table if not exists public.ffl_admin_state(id bigint primary key default 1,breaking_news text default '',announcement_title text,announcement_message text,maintenance boolean not null default false,updated_at timestamptz not null default now());
insert into public.ffl_admin_state(id) values(1) on conflict(id) do nothing;
create table if not exists public.ffl_admin_logs(id uuid primary key default gen_random_uuid(),action text not null,message text not null,created_at timestamptz not null default now());
create table if not exists public.ffl_standings(id uuid primary key default gen_random_uuid(),group_name text not null,team_name text not null,points integer not null default 0,played integer not null default 0,wins integer not null default 0,draws integer not null default 0,losses integer not null default 0,goals_for integer not null default 0,goals_against integer not null default 0,updated_at timestamptz not null default now(),unique(group_name,team_name));
create table if not exists public.ffl_matches(id uuid primary key default gen_random_uuid(),group_name text not null,home_team text not null,away_team text not null,home_score integer not null default 0,away_score integer not null default 0,status text not null default 'finished',match_date timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.fyfl_stats(id uuid primary key default gen_random_uuid(),player_name text not null,category text not null check(category in ('buteur','passeur')),value integer not null default 0,club text not null,club_logo_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
insert into public.ffl_standings(group_name,team_name) values
('A','Pays Bas'),('A','Italie'),('A','Uruguay'),('A','Égypte'),('B','Espagne'),('B','Argentine'),('B','Croatie'),('B','Norvège'),('C','Algérie'),('C','Colombie'),('C','Allemagne'),('C','Belgique'),('D','Sénégal'),('D','Japon'),('D','Tunisie'),('D','Brésil'),('E','Grèce'),('E','Angleterre'),('E','États Unis'),('E','Madagascar'),('F','Comores'),('F','Maroc'),('F','France'),('F','Canada') on conflict(group_name,team_name) do nothing;
alter table public.ffl_admin_state enable row level security;alter table public.ffl_admin_logs enable row level security;alter table public.ffl_standings enable row level security;alter table public.ffl_matches enable row level security;alter table public.fyfl_stats enable row level security;
drop policy if exists ffl_state_read on public.ffl_admin_state;create policy ffl_state_read on public.ffl_admin_state for select to anon,authenticated using(true);
drop policy if exists ffl_logs_read on public.ffl_admin_logs;create policy ffl_logs_read on public.ffl_admin_logs for select to anon,authenticated using(true);
drop policy if exists ffl_stand_read on public.ffl_standings;create policy ffl_stand_read on public.ffl_standings for select to anon,authenticated using(true);
drop policy if exists ffl_match_read on public.ffl_matches;create policy ffl_match_read on public.ffl_matches for select to anon,authenticated using(true);
drop policy if exists ffl_stats_read on public.fyfl_stats;create policy ffl_stats_read on public.fyfl_stats for select to anon,authenticated using(true);
alter table public.ffl_admin_state replica identity full;alter table public.ffl_standings replica identity full;alter table public.ffl_matches replica identity full;alter table public.fyfl_stats replica identity full;
do $$begin alter publication supabase_realtime add table public.ffl_admin_state;exception when duplicate_object then null;end$$;do $$begin alter publication supabase_realtime add table public.ffl_standings;exception when duplicate_object then null;end$$;do $$begin alter publication supabase_realtime add table public.ffl_matches;exception when duplicate_object then null;end$$;do $$begin alter publication supabase_realtime add table public.fyfl_stats;exception when duplicate_object then null;end$$;
