-- FFL: admin realtime + classement coupe du monde
create table if not exists public.ffl_admin_state (id bigint primary key, breaking_news text not null default 'Bienvenue sur le site de la FFL — la Coupe du Monde est en cours.', announcement_title text, announcement_message text, maintenance boolean not null default false, updated_at timestamptz not null default now());
insert into public.ffl_admin_state(id) values(1) on conflict(id) do nothing;
create table if not exists public.ffl_admin_logs (id bigint generated by default as identity primary key, action text not null, message text not null, created_at timestamptz not null default now());
create table if not exists public.ffl_standings (id bigint generated by default as identity primary key, group_name text not null check(group_name in ('A','B','C','D','E','F')), team_name text not null, points int not null default 0, played int not null default 0, wins int not null default 0, draws int not null default 0, losses int not null default 0, goals_for int not null default 0, goals_against int not null default 0, unique(group_name,team_name));
alter table public.ffl_admin_state enable row level security; alter table public.ffl_admin_logs enable row level security; alter table public.ffl_standings enable row level security;
drop policy if exists "public can read FFL admin state" on public.ffl_admin_state; create policy "public can read FFL admin state" on public.ffl_admin_state for select to anon,authenticated using(true);
drop policy if exists "public can read FFL admin logs" on public.ffl_admin_logs; create policy "public can read FFL admin logs" on public.ffl_admin_logs for select to anon,authenticated using(true);
drop policy if exists "public can read FFL standings" on public.ffl_standings; create policy "public can read FFL standings" on public.ffl_standings for select to anon,authenticated using(true);
insert into public.ffl_standings(group_name,team_name,points,played,wins,draws,losses,goals_for,goals_against) values
('A','Pays Bas',3,1,1,0,0,7,0),('A','Italie',3,1,1,0,0,5,0),('A','Uruguay',0,1,0,0,1,0,5),('A','Égypte',0,1,0,0,1,0,7),
('B','Espagne',3,1,1,0,0,7,4),('B','Argentine',3,1,1,0,0,3,2),('B','Croatie',0,1,0,0,1,2,3),('B','Norvège',0,1,0,0,1,4,7),
('C','Algérie',3,1,1,0,0,10,1),('C','Colombie',0,0,0,0,0,0,0),('C','Allemagne',0,0,0,0,0,0,0),('C','Belgique',0,1,0,0,1,1,10),
('D','Sénégal',3,1,1,0,0,4,0),('D','Japon',0,0,0,0,0,0,0),('D','Tunisie',0,0,0,0,0,0,0),('D','Brésil',0,1,0,0,1,0,4),
('E','Grèce',3,1,1,0,0,5,4),('E','Angleterre',0,0,0,0,0,0,0),('E','États Unis',0,0,0,0,0,0,0),('E','Madagascar',0,1,0,0,1,4,5),
('F','Comores',3,1,1,0,0,3,0),('F','Maroc',0,0,0,0,0,0,0),('F','France',0,0,0,0,0,0,0),('F','Canada',0,1,0,0,1,0,3)
on conflict(group_name,team_name) do update set points=excluded.points, played=excluded.played, wins=excluded.wins, draws=excluded.draws, losses=excluded.losses, goals_for=excluded.goals_for, goals_against=excluded.goals_against;
do $$ begin alter publication supabase_realtime add table public.ffl_admin_state; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.ffl_standings; exception when duplicate_object then null; end $$;
