-- =========================================================
-- FFL - SUPABASE COMPLET + REALTIME
-- À exécuter dans Supabase > SQL Editor
-- =========================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------
-- ÉTAT GLOBAL DU SITE
-- ---------------------------------------------------------
create table if not exists public.ffl_admin_state (
  id bigint primary key,
  breaking_news text not null default 'Bienvenue sur le site de la FFL — la Coupe du Monde est en cours.',
  announcement_title text,
  announcement_message text,
  maintenance boolean not null default false,
  updated_at timestamptz not null default now()
);

alter table public.ffl_admin_state add column if not exists breaking_news text not null default 'Bienvenue sur le site de la FFL — la Coupe du Monde est en cours.';
alter table public.ffl_admin_state add column if not exists announcement_title text;
alter table public.ffl_admin_state add column if not exists announcement_message text;
alter table public.ffl_admin_state add column if not exists maintenance boolean not null default false;
alter table public.ffl_admin_state add column if not exists updated_at timestamptz not null default now();

insert into public.ffl_admin_state(id) values (1) on conflict(id) do nothing;

-- ---------------------------------------------------------
-- JOURNAL ADMIN
-- ---------------------------------------------------------
create table if not exists public.ffl_admin_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  message text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------
-- CLASSEMENT
-- ---------------------------------------------------------
create table if not exists public.ffl_standings (
  id bigint generated by default as identity primary key,
  group_name text not null check(group_name in ('A','B','C','D','E','F')),
  team_name text not null,
  points int not null default 0,
  played int not null default 0,
  wins int not null default 0,
  draws int not null default 0,
  losses int not null default 0,
  goals_for int not null default 0,
  goals_against int not null default 0,
  updated_at timestamptz not null default now(),
  unique(group_name, team_name)
);

alter table public.ffl_standings add column if not exists updated_at timestamptz not null default now();

-- ---------------------------------------------------------
-- MATCHS
-- ---------------------------------------------------------
create table if not exists public.ffl_matches (
  id uuid primary key default gen_random_uuid(),
  group_name text not null check(group_name in ('A','B','C','D','E','F')),
  home_team text not null,
  away_team text not null,
  home_score integer not null default 0 check(home_score >= 0),
  away_score integer not null default 0 check(away_score >= 0),
  status text not null default 'finished' check(status in ('upcoming','live','finished')),
  match_date timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check(home_team <> away_team)
);

-- ---------------------------------------------------------
-- STATS JOUEURS
-- ---------------------------------------------------------
create table if not exists public.fyfl_stats (
  id uuid primary key default gen_random_uuid(),
  player_name text not null,
  category text not null check(category in ('buteur','passeur')),
  value integer not null default 0 check(value >= 0),
  club text not null,
  club_logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Si fyfl_stats existait déjà avec une ancienne structure, on complète les colonnes.
alter table public.fyfl_stats add column if not exists player_name text;
alter table public.fyfl_stats add column if not exists category text;
alter table public.fyfl_stats add column if not exists value integer default 0;
alter table public.fyfl_stats add column if not exists club text;
alter table public.fyfl_stats add column if not exists club_logo_url text;
alter table public.fyfl_stats add column if not exists created_at timestamptz not null default now();
alter table public.fyfl_stats add column if not exists updated_at timestamptz not null default now();

-- ---------------------------------------------------------
-- updated_at
-- ---------------------------------------------------------
create or replace function public.ffl_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists ffl_admin_state_touch on public.ffl_admin_state;
create trigger ffl_admin_state_touch before update on public.ffl_admin_state
for each row execute function public.ffl_touch_updated_at();

drop trigger if exists ffl_standings_touch on public.ffl_standings;
create trigger ffl_standings_touch before update on public.ffl_standings
for each row execute function public.ffl_touch_updated_at();

drop trigger if exists ffl_matches_touch on public.ffl_matches;
create trigger ffl_matches_touch before update on public.ffl_matches
for each row execute function public.ffl_touch_updated_at();

drop trigger if exists fyfl_stats_touch on public.fyfl_stats;
create trigger fyfl_stats_touch before update on public.fyfl_stats
for each row execute function public.ffl_touch_updated_at();

-- ---------------------------------------------------------
-- DONNÉES DE DÉPART DU CLASSEMENT
-- ---------------------------------------------------------
insert into public.ffl_standings(group_name,team_name,points,played,wins,draws,losses,goals_for,goals_against) values
('A','Pays Bas',3,1,1,0,0,7,0),('A','Italie',3,1,1,0,0,5,0),('A','Uruguay',0,1,0,0,1,0,5),('A','Égypte',0,1,0,0,1,0,7),
('B','Espagne',3,1,1,0,0,7,4),('B','Argentine',3,1,1,0,0,3,2),('B','Croatie',0,1,0,0,1,2,3),('B','Norvège',0,1,0,0,1,4,7),
('C','Algérie',3,1,1,0,0,10,1),('C','Colombie',0,0,0,0,0,0,0),('C','Allemagne',0,0,0,0,0,0,0),('C','Belgique',0,1,0,0,1,1,10),
('D','Sénégal',3,1,1,0,0,4,0),('D','Japon',0,0,0,0,0,0,0),('D','Tunisie',0,0,0,0,0,0,0),('D','Brésil',0,1,0,0,1,0,4),
('E','Grèce',3,1,1,0,0,5,4),('E','Angleterre',0,0,0,0,0,0,0),('E','États Unis',0,0,0,0,0,0,0),('E','Madagascar',0,1,0,0,1,4,5),
('F','Comores',3,1,1,0,0,3,0),('F','Maroc',0,0,0,0,0,0,0),('F','France',0,0,0,0,0,0,0),('F','Canada',0,1,0,0,1,0,3)
on conflict(group_name,team_name) do nothing;

-- ---------------------------------------------------------
-- RLS : lecture publique. Les écritures admin passent par
-- l'API Vercel avec la service role key.
-- ---------------------------------------------------------
alter table public.ffl_admin_state enable row level security;
alter table public.ffl_admin_logs enable row level security;
alter table public.ffl_standings enable row level security;
alter table public.ffl_matches enable row level security;
alter table public.fyfl_stats enable row level security;

drop policy if exists "ffl admin state public read" on public.ffl_admin_state;
create policy "ffl admin state public read" on public.ffl_admin_state
for select to anon, authenticated using (true);

drop policy if exists "ffl logs public read" on public.ffl_admin_logs;
create policy "ffl logs public read" on public.ffl_admin_logs
for select to anon, authenticated using (true);

drop policy if exists "ffl standings public read" on public.ffl_standings;
create policy "ffl standings public read" on public.ffl_standings
for select to anon, authenticated using (true);

drop policy if exists "ffl matches public read" on public.ffl_matches;
create policy "ffl matches public read" on public.ffl_matches
for select to anon, authenticated using (true);

drop policy if exists "fyfl stats public read" on public.fyfl_stats;
drop policy if exists "fyfl stats public insert" on public.fyfl_stats;
drop policy if exists "fyfl stats public update" on public.fyfl_stats;
drop policy if exists "fyfl stats public delete" on public.fyfl_stats;
drop policy if exists "fyfl stats read" on public.fyfl_stats;
drop policy if exists "fyfl stats insert" on public.fyfl_stats;
drop policy if exists "fyfl stats update" on public.fyfl_stats;
drop policy if exists "fyfl stats delete" on public.fyfl_stats;
create policy "fyfl stats public read" on public.fyfl_stats
for select to anon, authenticated using (true);

-- ---------------------------------------------------------
-- REALTIME
-- ---------------------------------------------------------
do $$ begin alter publication supabase_realtime add table public.ffl_admin_state; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.ffl_admin_logs; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.ffl_standings; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.ffl_matches; exception when duplicate_object then null; end $$;
do $$ begin alter publication supabase_realtime add table public.fyfl_stats; exception when duplicate_object then null; end $$;

alter table public.ffl_admin_state replica identity full;
alter table public.ffl_admin_logs replica identity full;
alter table public.ffl_standings replica identity full;
alter table public.ffl_matches replica identity full;
alter table public.fyfl_stats replica identity full;

create index if not exists ffl_matches_created_idx on public.ffl_matches(created_at desc);
create index if not exists ffl_stats_category_value_idx on public.fyfl_stats(category, value desc);
create index if not exists ffl_logs_created_idx on public.ffl_admin_logs(created_at desc);
